version: 2

updates:
    - package-ecosystem: "gomod"
      directory: /
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch
      groups:
          gomod-breaking-changes:
              patterns:
                  - "*"
              update-types:
                  - major

    - package-ecosystem: "docker"
      directory: /
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch
      groups:
          docker-breaking-changes:
              patterns:
                  - "*"
              update-types:
                  - major

    - package-ecosystem: "github-actions"
      directory: /
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-minor
                - version-update:semver-patch
      groups:
          github-actions-breaking-changes:
              patterns:
                  - "*"
              update-types:
                  - major
