linters:
    enable:
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose
        - containedctx
        - contextcheck
        - cyclop
        - decorder
        - dogsled
        - dupl
        - dupword
        - durationcheck
        - errchkjson
        - errname
        - errorlint
        - exportloopref
        - forbidigo
        - forcetypeassert
        - funlen
        - gci
        - gocheckcompilerdirectives
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - godox
        - goerr113
        - gofmt
        - gofumpt
        - goheader
        - goimports
        - gomnd
        - gomoddirectives
        - goprintffuncname
        - gosec
        - grouper
        - importas
        - interfacebloat
        - lll
        - loggercheck
        - maintidx
        - makezero
        - mirror
        - misspell
        - musttag
        - nakedret
        - nestif
        - nilerr
        - nilnil
        - noctx
        - nolintlint
        - nonamedreturns
        - nosprintfhostport
        - paralleltest
        - prealloc
        - predeclared
        - reassign
        - revive
        - stylecheck
        - tagalign
        - tagliatelle
        - tenv
        - testpackage
        - thelper
        - tparallel
        - unconvert
        - unparam
        - usestdlibvars
        - wastedassign
        - whitespace

issues:
    exclude-rules:
        - path: (.+)_test.go
          linters:
              - forcetypeassert
              - goerr113

linters-settings:
    errcheck:
        exclude-functions:
            - github.com/go-chi/render.Render
    gosec:
        excludes:
            - G107
