linters:
    enable:
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose
        - containedctx
        - contextcheck
        - cyclop
        - decorder
        # - depguard
        - dogsled
        - dupl
        - dupword
        - durationcheck
        - errchkjson
        - errname
        - errorlint
        - execinquery
        # - exhaustive
        # - exhaustruct
        - exportloopref
        - forbidigo
        - forcetypeassert
        - funlen
        - gci
        - ginkgolinter
        - gocheckcompilerdirectives
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - godox
        - goerr113
        - gofmt
        - gofumpt
        - goheader
        - goimports
        - gomnd
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - gosec
        - gosmopolitan
        - grouper
        - importas
        - interfacebloat
        # - ireturn
        - lll
        - loggercheck
        - maintidx
        - makezero
        - mirror
        - misspell
        - musttag
        - nakedret
        - nestif
        - nilerr
        - nilnil
        # - nlreturn
        # - noctx
        - nolintlint
        - nonamedreturns
        - nosprintfhostport
        - paralleltest
        - prealloc
        - predeclared
        - promlinter
        - reassign
        - revive
        - rowserrcheck
        - sqlclosecheck
        - stylecheck
        - tagalign
        - tagliatelle
        - tenv
        - testableexamples
        - testpackage
        - thelper
        - tparallel
        - unconvert
        - unparam
        - usestdlibvars
        # - varnamelen
        - wastedassign
        - whitespace
        # - wrapcheck
        # - wsl
        # - zerologlint

issues:
    exclude-rules:
        - path: (.+)_test.go
          linters:
              - forcetypeassert
              - goerr113

linters-settings:
    gosec:
        excludes:
            - G107
