name: CI

on:
    push:
        branches:
            - main
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Prettier
              uses: actionsx/prettier@v2
              with:
                  args: --check .

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.20"

            - name: Lint
              uses: golangci/golangci-lint-action@v3
              with:
                  skip-pkg-cache: true

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build images
              uses: docker/bake-action@v3
              with:
                  load: true
                  files: docker-compose.test.yml
                  set: |
                      app.cache-from=type=gha,scope=$GITHUB_REF_NAME-app
                      app.cache-to=type=gha,scope=$GITHUB_REF_NAME-app,mode=max
                      test-e2e.cache-from=type=gha,scope=$GITHUB_REF_NAME-test-e2e
                      test-e2e.cache-to=type=gha,scope=$GITHUB_REF_NAME-test-e2e,mode=max
                      test-unit.cache-from=type=gha,scope=$GITHUB_REF_NAME-test-unit
                      test-unit.cache-to=type=gha,scope=$GITHUB_REF_NAME-test-unit,mode=max

            - name: Test
              run: |
                  docker compose -f docker-compose.test.yml run --rm test-unit
                  docker compose -f docker-compose.test.yml run --rm test-e2e

            - name: Upload coverage report
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage/coverage.out
                  fail_ci_if_error: true # optional (default = false)

    release:
        runs-on: ubuntu-latest

        if: github.event_name == 'push'

        needs:
            - lint
            - test

        permissions:
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Metadata
              id: docker-metadata
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/murar8/local-jwks-server
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}
                      type=edge,branch=main
                      type=sha,prefix=

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{ steps.docker-metadata.outputs.tags }}
                  labels: ${{ steps.docker-metadata.outputs.labels }}
                  cache-from: type=gha,scope=$GITHUB_REF_NAME-app
                  cache-to: type=gha,scope=$GITHUB_REF_NAME-app,mode=max
