name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Pre Commit
              uses: pre-commit/action@v3.0.1
