name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.x"

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: "^1.24.3"

            - name: Pre Commit
              uses: cloudposse/github-action-pre-commit@v4.0.0
