name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Pre Commit
              uses: pre-commit/action@v3.0.0
