name: Release

on:
    workflow_call:

jobs:
    release:
        runs-on: ubuntu-latest

        if: github.event_name == 'push'

        permissions:
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Metadata
              id: docker-metadata
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/murar8/local-jwks-server
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}
                      type=edge,branch=main
                      type=sha,prefix=

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{ steps.docker-metadata.outputs.tags }}
                  labels: ${{ steps.docker-metadata.outputs.labels }}
                  cache-from: type=gha,scope=$GITHUB_REF_NAME-app
                  cache-to: type=gha,scope=$GITHUB_REF_NAME-app,mode=max
