name: Release

on:
    workflow_call:

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Metadata
              id: docker-metadata
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository_owner }}/local-jwks-server
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}
                      type=edge,branch=main
                      type=sha,prefix=

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.docker-metadata.outputs.tags }}
                  labels: ${{ steps.docker-metadata.outputs.labels }}
                  cache-from: type=gha,scope=$GITHUB_REF_NAME-app
                  cache-to: type=gha,scope=$GITHUB_REF_NAME-app,mode=max
